# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

pool:
  vmImage: "ubuntu-20.04"

resources:
  - repo: self

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'docker/pylith-testenv'
    arguments: '--build-arg BASE_IMAGE=registry.gitlab.com/cig-pylith/pylith_installer/debian-stable --target build'
    dockerfile: "docker/pylith-testenv"
    addPipelineData: false
    addBaseImageData: false
